### ISSUE TITLE
ERROR: Unknown tag RG!

### ISSUE THREAD

**Issue by JoseFrancoAlvarez** [nygenome/nygc-short-alignment-marking#1]
Hi,

I was trying to use the tool filter_bam, I am having some troubles. The code I am using is:

filter_bam -I Sample_CH112-3_merged_bam.bam -A1 30 -A2 30 -o Sample_CH112-3_merged_bam_30bp.bam | samtools view -b -o Sample_CH112-3_merged_bam_30bp.bam

I merged all my bam files from the same sample in only one using samtools merge in a previous step, and the output I am getting using filter_bam is:

[W::sam_parse1] empty query name
[W::sam_parse1] empty query name
[W::sam_parse1] empty query name
[W::sam_parse1] empty query name
[W::sam_parse1] empty query name
[W::sam_parse1] empty query name
ERROR: Unknown tag RG!

I have checked the reads have the RG.

Thanks in advance.

**Comment by shahmj** [comment]
Hi @JoseFrancoAlvarez, sorry for the late response, I was away with intermittent wifi access.
Is your bam file read sorted? The program expects a read sorted bam so that all read pairs and any associated secondary alignments can be looked at together.

**Comment by JoseFrancoAlvarez** [comment]
Hi @shahmj, and thank you for your reply. What happened if I do not sort the bam file? I tried different things, and finally if i do not merge all bam files before, and just I do filter_bam for each individual bam file it works, but I havent sorted the indidivual bam files before. It is wrong? Thank you for your help.

**Comment by shahmj** [comment]
Good to know it works on the individual bams. You can either run filter_bam on the individual bams and then merge and sort (by coordinate) after or merge (sorted by read name, samtools merge -n), run filter_bam and then resort by coordinate whichever works for you.
